# Generated by Django 3.2 on 2021-05-20 12:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='form_builder.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('last_saved', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.IntegerField()),
                ('label', models.TextField()),
                ('label_type', models.CharField(max_length=20)),
                ('criteria', models.TextField()),
                ('outcome_title', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='form_builder.competency')),
            ],
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_type', models.CharField(max_length=2)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='form_builder.performance')),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_builder.form'),
        ),
    ]
